services:
  - type: web
    name: vin-extraction-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app -b 0.0.0.0:10000 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
